# This is the network config written by 'subiquity'
# Dynamic IP address
network:
  ethernets:
    enp0s3:
      dhcp4: true
# Static IP address
    enp0s8:
      dhcp4: false
      addresses: [192.168.0.77/24]
      gateway4: 192.168.0.2
      nameservers:
       addresses: [8.8.8.8,8.8.4.4]
  version: 2

